name: seq_logger
description: The package that writes the logs to the database and sends these logs to the SEQ LOG Api service.
version: 1.0.4
repository: https://github.com/Performans-Dev/seq_logger/
environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  intl: ^0.17.0
  path: ^1.8.2
  path_provider: ^2.0.11
  sqflite: ^2.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

